services:
  # Check out https://render.com/docs/blueprint-spec for more details
  - type: web
    name: pern-todo-backend
    env: node
    region: oregon 
    plan: free 
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    branch: main 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pern-todo-db
          property: connectionString
      - key: PORT
        value: 10000

  - type: static
    name: pern-todo-frontend
    env: static
    region: oregon 
    plan: free 
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    branch: main 
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: pern-todo-backend
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: pern-todo-db
    databaseName: perntodo
    user: perntodo_user
    plan: free 
    region: oregon 
